-- MySQL Script generated by MySQL Workbench
-- 05/30/16 23:32:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sena_db
-- -----------------------------------------------------
-- マスタ関連
-- -----------------------------------------------------
-- Schema sena_secure_db
-- -----------------------------------------------------
-- ユーザー関連
CREATE SCHEMA IF NOT EXISTS `sena_secure_db` ;
USE `sena_secure_db` ;

-- -----------------------------------------------------
-- Table `sena_secure_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_secure_db`.`users` ;

CREATE TABLE IF NOT EXISTS `sena_secure_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `account_id` VARCHAR(20) BINARY NOT NULL COMMENT 'アカウントID',
  `password` VARCHAR(20) BINARY NOT NULL COMMENT 'パスワード',
  `nickname` VARCHAR(20) NOT NULL COMMENT 'ニックネーム',
  `access_token` VARCHAR(128) BINARY NOT NULL COMMENT 'アクセストークン',
  `use_datetime` DATETIME NOT NULL COMMENT '利用日時',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（1：削除、0：未削除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'ユーザー';

CREATE INDEX `i_users1` ON `sena_secure_db`.`users` (`delete_flg` ASC, `access_token` ASC);

CREATE INDEX `i_users2` ON `sena_secure_db`.`users` (`delete_flg` ASC, `account_id` ASC, `password` ASC);

CREATE INDEX `i_users3` ON `sena_secure_db`.`users` (`delete_flg` ASC, `account_id` ASC);


-- -----------------------------------------------------
-- Table `sena_secure_db`.`account_stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_secure_db`.`account_stocks` ;

CREATE TABLE IF NOT EXISTS `sena_secure_db`.`account_stocks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `users_id` BIGINT NOT NULL,
  `date` DATE NOT NULL COMMENT '取得日',
  `stock_code` INT NOT NULL COMMENT '銘柄コード',
  `type` INT NOT NULL COMMENT '取引種別（1..国内株式、2..金額・株数指定取引、3..信用建玉（買建）、4..信用建玉（売建））',
  `amount` DECIMAL(25,10) NOT NULL COMMENT '保有株数（整数部：15桁、小数部：10桁）',
  `average_cost` DECIMAL(25,10) NOT NULL COMMENT '平均取得単価（整数部：15桁、小数部：10桁）',
  `current_value` DECIMAL(20,5) NOT NULL COMMENT '現在値（整数部：15桁、小数部：5桁）',
  `market_value` DECIMAL(25,10) NOT NULL COMMENT '時価評価額（「保有株数 * 現在値」で算出された値、整数部：15桁、小数部：10桁）',
  `gain_loss` DECIMAL(25,10) NOT NULL COMMENT '評価損益（「（保有株数 * 現在値） - （保有株数 * 平均取得単価）」で算出された値、整数部：15桁、小数部：10桁）',
  `gain_loss_rate` DECIMAL(10,2) NOT NULL COMMENT '損益率（「（評価損益 / （保有株数 * 現在値）） * 100」で算出された値、整数部：8桁、小数部：2桁）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（1：削除、0：未削除）',
  PRIMARY KEY (`id`, `users_id`))
ENGINE = InnoDB
COMMENT = '口座銘柄';

CREATE INDEX `fk_account_stocks_users_idx` ON `sena_secure_db`.`account_stocks` (`users_id` ASC);

CREATE INDEX `fk_account_stocks_stocks1_idx` ON `sena_secure_db`.`account_stocks` (`stock_code` ASC);

CREATE INDEX `i_account_stocks1` ON `sena_secure_db`.`account_stocks` (`delete_flg` ASC, `users_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
